JonathanSalwan/ROPgadget

- ropgadget/gadgets.py
- test-suite-binaries/test.sh
This pull request is to improve the performance of the tool since instead of call `self.__binary.getArch()` for each gadget is called once and used when is necessary. 
In the function `__gadgetsFinding` is create only once instance of Capstone and only is disassemble when the alignment is correct in this way we save time of computation.
> Improve performance

- ropgadget/gadgets.py
Before this change, I get "Can't find the 'syscall' instruction". After it, a ropchain can be build successfully.
> prevent `syscall` from being filtered

- ropgadget/loaders/raw.py
In python3 we get the following error when we use RAW loader:
```
TypeError: cannot use a bytes pattern on a string-like object
```
> Fix RAW loader's opcodes type

- ropgadget/options.py
- --badbytes worked only on python2 it seems. It called decode()
on strings, which does not work in py3 anymore. Moved to using
codecs module, which should work in all cases.
> Make --badbytes portable across python versions

- ropgadget/core.py
- ropgadget/options.py
My colleague say that he want to input more than one re to get the gadget. So i change the code.
for example:
(ROPgadget)> re mov r\d+, sp | bx lr
[+] Re setted. You have to reload gadgets
(ROPgadget)> load
[+] Loading gadgets, please wait...
[+] Gadgets loaded !
(ROPgadget)> display
Gadgets information
============================================================
0x000218d4 : **bx lr** ; mov ip, r7 ; mov r2, r1 ; mov r1, #1 ; mov r7, #0xf0 ; svc #0 ; mov r7, ip ; **bx lr** ; **mov r0, sp** ; **bx lr**
...
...
0x000218e4 : mov r7, #0xf0 ; svc #0 ; mov r7, ip ; **bx lr** ; **mov r0, sp** ; **bx lr**
0x000218ec : mov r7, ip ; **bx lr** ; **mov r0, sp** ; **bx lr**
0x000218e8 : svc #0 ; mov r7, ip ; **bx lr** ; **mov r0, sp** ; **bx lr**
Unique gadgets found: 9
> input more one re

- ropgadget/gadgets.py
Hi,
I think that I spotted a small bug in the process of creating gadgets.
When creating a gadget from a pattern, the backward dissas does not check if the last instruction generated is the same as the pattern.
In the example [test.txt](https://github.com/JonathanSalwan/ROPgadget/files/381738/test.txt), there are two instructions :
```bash
add ebx, ebp
ret 0x2e66
```
As hex: "01ebc2662e".
Which matches the [pattern](https://github.com/JonathanSalwan/ROPgadget/blob/master/ropgadget/gadgets.py#L88) [\xc2[\x00-\xff]{2}] 
Yet if you try to disassemble from the octet  "eb", you have "ebc2", which is a jump.
Then 66 2e are just garbages values.
Gadgets generated without the fix :
```bash
ROPgadget.py --binary test --depth 3 --dump
...
0x0000000000400080 : add ebx, ebp ; ret 0x2e66 // 01ebc2662e …
```
> Inconsistencies of created gadgets, due to backward dissas

- ropgadget/loaders/pe.py
https://github.com/JonathanSalwan/ROPgadget/issues/77
Due to invalid IMAGE_OPTIONAL_HEADER64 definition, ROPGadget reports
wrong addresses for x64 PE files.
> Fixed issue #77

- ropgadget/gadgets.py
The JOP patterns for ARM64 missed a set of registers, for example, blr x8 and br x8 were missed. This PR fixes it by adding the relevant bit to the pattern.
> Support additional registers in ARM64 JOP patterns

- ropgadget/options.py
`__deleteBadBytes` in options.py uses `str.decode("hex")`
Replaced this with `codec.decode(str, "hex")`
> BadBytes python3 compatability

- ropgadget/core.py
Opcodes can contains hexadecimal values whose associated ASCII characters corresponds
to special characters interpreted as part of a regular expression (typically 0x5B='[').
Calling re.escape before using the opcodes, will escape all these characters, leaving
others unchanged.
> Fix opcode option.

- ropgadget/core.py
- ropgadget/gadgets.py
*Symptom*:
The logic before is like this:
1. find all gadgets in the whole binary
2. delete duplicates gadget and sort gadgets
3. look for desired gadget within the range
there are two problems of this implementation
1. wrong logic.
we want gadgets within the range,  but those gadgets could be duplicates of previous gadgets. But duplicates have been deleted in step2. So we actually get much less gadgets and those missing gadgets  could be the most common ones.
2. takes too much time.
Now that we want everything within the range, why bother going through the whole binary?
*Fix*
The new implementation works like this.
Each time we want a section(should be a segment?), we take the intersection of the search range and the section and modify `offset`,`vaddr` and `size` accordingly. In this …
> fix wrong search in range implementation

- ropgadget/core.py
```bash
eg. ROPgadget --binary /bin/ls --dump --all --depth 6
```
Generates the following stack trace
```python
============================================================
Traceback (most recent call last):
File "/usr/local/bin/ROPgadget", line 4, in <module>
__import__('pkg_resources').run_script('ROPGadget==5.7', 'ROPgadget')
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1460, in run_script
exec(script_code, namespace, namespace)
File "/usr/local/lib/python3.7/site-packages/ROPGadget-5.7-py3.7.egg/EGG-INFO/scripts/ROPgadget", line 12, in <module>
File …
```
> Fix issue with python 3.7.5

- ropgadget/gadgets.py
Only `ra` and `t9` jumps were supported on MIPS. I added jumps on other registers. Also supported MIPS `j addr` for this interesting gadget:
```
j 0xdeadbeef
lw $v0, 0($v1)  <- delay slot
0xdeadbeef:
lw $ra, 16($sp)
jr $ra
addiu $sp, $sp, 28  <- delay slot
```
This gadgets loads value into `v0` from stack and jumps to the second part that transfers control to the next gadget address taken from stack.
> More JOP gadgets

- ropgadget/args.py
- ropgadget/core.py
Hi,
I added a `--silent` option which disables printing during analysis. The flag is off by default in order to keep the current behaviour.
This is handy when integrating ropgadget into my own scripts in a programmatic manner to not clutter the output.
> add option to disable text output during analysis

- README.md
- ropgadget/args.py
- ropgadget/core.py
this helps to find useful gadgets for mips, its inspired by https://github.com/tacnetsol/ida/tree/master/plugins/mipsrop
searches based on regexes
this was made after iceCTF with @harsh_khuha
_____
available options for --mipsrop arg
registers
gadgets that put stack values into a register. (useful to control registers values)
stackfinder
gadgets that put a stack address into a register. (useful to load shellcode address into register)
system
gadgets that put a stack address into $a0. (useful to call system())
tails
tail call gadgets. (useful for function calls)
lia0
gadgets that load an immediate value number into $a0. (useful for setting up the argument to sleep)
> adding mipsrop

- ropgadget/binary.py
- ropgadget/loaders/macho.py
- ropgadget/loaders/pe.py
The loader for PE and Mach-O files relies on the native endianness of the host machine. This will fail when reading files for machines with a different endianness. This PR fixes all locations where the native endianness is applied.
This behavior was discovered during execution of the test suite on a PowerPC machine (big endian). See: https://bugs.gentoo.org/865149:
```
RUN core
RUN elf-ARM64-bash
RUN elf-ARMv7-ls
RUN elf-FreeBSD-x86
RUN elf-Linux-x64
RUN elf-Linux-x86
RUN elf-Linux-x86-NDH-chall
RUN elf-Mips-Defcon-20-pwn100
RUN elf-PowerPC-bash
RUN elf-PPC64-bash
RUN elf-SparcV8-bash
RUN elf-x64-bash-v4.1.5.1
RUN elf-x86-bash-v4.1.5.1
RUN Linux_lib32.so
RUN Linux_lib64.so
RUN macho-x64-ls
Traceback (most recent call last):
File "/var/tmp/portage/dev-util/ROPgadget-6.9/work/ROPgadget-6.9/t …
```
> Don't rely on native endianness

- ropgadget/gadgets.py
- test-suite-binaries/test.sh
Currently, ROPgadget does not include any pattern to detect LDM gadgets in Thumb mode for ARM. Such gadgets can be very useful for JOP in arm32 targets, and Thumb mode vastly increases their availability. LDM gadgets in Thumb2 (32-bit encoding) can also act as nice stack pivots, for instance:
```
ldm.w r8!, {r0, r1, r2, r3, r4, r5, r6, r7, r8, sb, fp, sp, lr, pc}
```
On the `elf-ARMv7-ls` test binary, running ROPgadget with `--thumb`, the number of gadgets found increases from 131 to 2387, and the number of `ldm.w` gadgets (`--only ldm.w`) increases from 0 to 29.
> Add LDM / LDMDB JOP gadgets for ARM Thumb2

- ropgadget/updateAlert.py
`SyntaxWarning: invalid escape sequence '\d'`
> Fix SyntaxWarning in Python 3.13

- ropgadget/gadgets.py
- ropgadget/ropchain/arch/ropmakerx64.py
- ropgadget/ropchain/arch/ropmakerx86.py
Following #209, this fixes two runtime warnings:
* `SyntaxWarning: invalid escape sequence '\?'`, and
* `SyntaxWarning: invalid escape sequence '\['`
You can see that escaping `?` was indeed intentional by considering that the arm instruction `blr reg` is 32-bit wide and follows [this format](https://www.scs.stanford.edu/~zyedidia/arm64/blr.html). I replaced `\?` with `\x3f` because `chr(0x3f) == '?'`.
> Fix more SyntaxWarnings in Python 3.13

- ropgadget/options.py
```
$ python ROPgadget.py --binary ntdll.dll --callPreceded | head -10
Options().removeNonCallPreceded(): Filtered out 70230 gadgets.
Gadgets information
============================================================
0x00000001800c2bcc : adc ah, al ; std ; call qword ptr [rax - 0x5268d17]
0x0000000180018016 : adc al, 0 ; add al, byte ptr [rax] ; add byte ptr [rax], al ; jmp 0x180017ffb
0x000000018001802e : adc al, 0 ; jmp 0x180017ff6
0x00000001801071d8 : adc al, 0x1a ; add byte ptr [rax], al ; jmp 0x1801072e6
0x000000018000d82e : adc al, 0x24 ; xor r12d, r12d ; jmp 0x18000cfbf
0x000000018005a648 : adc al, 0x41 ; add al, 0 ; jmp 0x18005a607
0x00000001800c9b94 : adc al, 0x42 ; jne 0x1800c9b8e ; lea r11d, [rax + 1] ; jmp 0x1800827bb
```
> fix callPreceded filtering (#213)
